/**
 * uploadLab.ts — multer diskStorage configuration for lab file uploads (PDF/JPG/PNG).
 *
 * LAB-05: supports PDF, JPEG, and PNG uploads with 10MB limit.
 * Storage path: /app/uploads/lab-files/ (Docker volume mounted via docker-compose.yml).
 * Files are renamed to <uuid>.<ext> for collision-free serving via GET /api/lab/file/:id.
 */
import multer from "multer";
import path from "node:path";
import fs from "node:fs";
import { randomUUID } from "node:crypto";

const UPLOAD_DIR = process.env.UPLOAD_DIR_LAB ?? "/app/uploads/lab-files";

// Ensure the upload directory exists
try {
  fs.mkdirSync(UPLOAD_DIR, { recursive: true });
} catch {
  // Fail silently — when running inside Docker the volume mount provides this directory.
}

const storage = multer.diskStorage({
  destination: (_req, _file, cb) => {
    cb(null, UPLOAD_DIR);
  },
  filename: (_req, file, cb) => {
    // Generate a UUID-based filename to use as the fileId reference
    const uuid = randomUUID();
    const ext = path.extname(file.originalname).toLowerCase();
    cb(null, `${uuid}${ext}`);
  },
});

/**
 * fileFilter — reject uploads that are not PDF, JPEG, or PNG.
 */
const fileFilter: multer.Options["fileFilter"] = (_req, file, cb) => {
  const allowedMime = [
    "application/pdf",
    "image/jpeg",
    "image/png",
  ];
  if (allowedMime.includes(file.mimetype)) {
    cb(null, true);
  } else {
    cb(new Error("Hanya file PDF, JPEG, atau PNG yang diizinkan") as any, false);
  }
};

/**
 * labFileUpload — configured multer instance for lab document uploads.
 * Use as `labFileUpload.single("file")` in lab routes.
 *
 * The filename generated by diskStorage is a UUID + original extension,
 * which doubles as the `fileId` reference stored in the lab_results row.
 */
export const labFileUpload = multer({
  storage,
  limits: {
    fileSize: 10 * 1024 * 1024, // 10MB (PRD 8.5)
  },
  fileFilter,
});

export default labFileUpload;
