/**
 * uploadLab.ts — multer diskStorage configuration for lab file uploads (PDF/JPG/PNG).
 *
 * LAB-05: supports PDF, JPEG, and PNG uploads with 10MB limit.
 * Storage path: <project-root>/uploads/lab-files/ (Docker volume mounted via
 * docker-compose.yml when running in a container).
 * Files are renamed to <uuid>.<ext> for collision-free serving via GET /api/lab/file/:id.
 *
 * quick-260707-1la item 11: this file previously hardcoded UPLOAD_DIR to the
 * Docker-only absolute path `/app/uploads/lab-files`, the same bug already
 * found and fixed for medication photos in `upload.ts` (quick-260706-573) —
 * that fix's own file header flagged this exact file as dormant-until-tested.
 * Deriving the path relative to __dirname (mirrors app.ts's static-serve path
 * `path.join(__dirname, "../uploads")`) keeps multer's write location and the
 * static server's read location in agreement whether running inside Docker
 * or locally via `npm run dev`.
 */
import multer from "multer";
import path from "node:path";
import fs from "node:fs";
import { randomUUID } from "node:crypto";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// src/lib -> ../.. -> project root -> uploads/lab-files
const DEFAULT_UPLOAD_DIR = path.join(__dirname, "../../uploads/lab-files");

// Exported so labResult.controller.ts (serveFile, uploadDelete) reads from
// the SAME directory this module writes to — never redefine independently.
export const UPLOAD_DIR = process.env.UPLOAD_DIR_LAB ?? DEFAULT_UPLOAD_DIR;

// Ensure the upload directory exists
try {
  fs.mkdirSync(UPLOAD_DIR, { recursive: true });
} catch {
  // Fail silently — when running inside Docker the volume mount provides this directory.
}

const storage = multer.diskStorage({
  destination: (_req, _file, cb) => {
    cb(null, UPLOAD_DIR);
  },
  filename: (_req, file, cb) => {
    // Generate a UUID-based filename to use as the fileId reference
    const uuid = randomUUID();
    const ext = path.extname(file.originalname).toLowerCase();
    cb(null, `${uuid}${ext}`);
  },
});

/**
 * fileFilter — reject uploads that are not PDF, JPEG, or PNG.
 */
const fileFilter: multer.Options["fileFilter"] = (_req, file, cb) => {
  const allowedMime = [
    "application/pdf",
    "image/jpeg",
    "image/png",
  ];
  if (allowedMime.includes(file.mimetype)) {
    cb(null, true);
  } else {
    cb(new Error("Hanya file PDF, JPEG, atau PNG yang diizinkan") as any, false);
  }
};

/**
 * labFileUpload — configured multer instance for lab document uploads.
 * Use as `labFileUpload.single("file")` in lab routes.
 *
 * The filename generated by diskStorage is a UUID + original extension,
 * which doubles as the `fileId` reference stored in the lab_results row.
 */
export const labFileUpload = multer({
  storage,
  limits: {
    fileSize: 10 * 1024 * 1024, // 10MB (PRD 8.5)
  },
  fileFilter,
});

export default labFileUpload;
