/**
 * labResult.controller.ts — Thin controller for lab result endpoints
 *
 * Pattern: follows fluid.controller.ts — parse req, delegate to service, json/next(err).
 * No business logic here.
 */
import type { Request, Response, NextFunction } from "express";
import path from "node:path";
import fs from "node:fs";
import * as labResultService from "../services/labResult.service.js";
import { verifyAccessToken, verifyRefreshToken } from "../utils/jwt.js";

const LAB_UPLOAD_DIR = process.env.UPLOAD_DIR_LAB ?? "/app/uploads/lab-files";

/**
 * POST /api/lab
 * Create a new manual lab result entry.
 */
export async function create(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const result = await labResultService.createEntry(req.user!.id, req.body);
    res.status(201).json(result);
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/lab
 * List lab results. Supports ?tanggal=YYYY-MM-DD and ?parameter= query params.
 */
export async function list(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const tanggal =
      typeof req.query.tanggal === "string" ? req.query.tanggal : undefined;
    const parameter =
      typeof req.query.parameter === "string" ? req.query.parameter : undefined;

    const results = await labResultService.listResults(req.user!.id, {
      tanggal,
      parameter,
    });
    res.json({ results });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/lab/parameters
 * Get distinct parameter names the user has logged.
 */
export async function getParameters(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const parameters = await labResultService.getDistinctParameters(req.user!.id);
    res.json({ parameters });
  } catch (err) {
    next(err);
  }
}

/**
 * PATCH /api/lab/:id/archive
 * Archive (soft-delete) a lab result.
 */
export async function archive(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const result = await labResultService.archiveResult(
      req.user!.id,
      req.params.id as string,
    );
    if (!result) {
      res.status(404).json({ code: "NOT_FOUND", message: "Lab result tidak ditemukan" });
      return;
    }
    res.json(result);
  } catch (err) {
    next(err);
  }
}

/**
 * PATCH /api/lab/:id/restore
 * Restore an archived lab result.
 */
export async function restore(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const result = await labResultService.restoreResult(
      req.user!.id,
      req.params.id as string,
    );
    if (!result) {
      res.status(404).json({ code: "NOT_FOUND", message: "Lab result tidak ditemukan" });
      return;
    }
    res.json(result);
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/lab/archived
 * List archived lab results only.
 */
export async function listArchived(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const results = await labResultService.listArchived(req.user!.id);
    res.json({ results });
  } catch (err) {
    next(err);
  }
}

/**
 * PUT /api/lab/:id
 * Update an existing manual lab result entry (editable fields only).
 */
export async function update(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const result = await labResultService.updateEntry(
      req.user!.id,
      req.params.id as string,
      req.body,
    );
    if (!result) {
      res.status(404).json({ code: "NOT_FOUND", message: "Lab result tidak ditemukan" });
      return;
    }
    res.json(result);
  } catch (err) {
    next(err);
  }
}

// ─── Upload (LAB-05) ──────────────────────────────────────────────────────────

/**
 * POST /api/lab/upload
 * Upload a lab document file (PDF/JPG/PNG) with tanggal pemeriksaan.
 * Expects multipart/form-data with fields:
 *   - file: the uploaded file
 *   - tanggalPemeriksaan: YYYY-MM-DD
 */
export async function upload(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    if (!req.file) {
      res.status(400).json({ code: "NO_FILE", message: "Tidak ada file yang diunggah" });
      return;
    }

    const tanggalPemeriksaan =
      (typeof req.body.tanggalPemeriksaan === "string"
        ? req.body.tanggalPemeriksaan
        : new Date(Date.now() + 7 * 3600 * 1000).toISOString().slice(0, 10));

    // User-provided display name for the uploaded document
    const namaFile =
      typeof req.body.namaFile === "string" ? req.body.namaFile : undefined;

    // The filename generated by multer diskStorage is UUID.ext — use as fileId (strip extension)
    const fileId = path.parse(req.file.filename).name;

    const result = await labResultService.createUploadEntry(
      req.user!.id,
      tanggalPemeriksaan,
      {
        fileId,
        originalName: req.file.originalname,
        mimeType: req.file.mimetype,
        fileSize: req.file.size,
        namaFile,
      },
    );

    res.status(201).json(result);
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/lab/file/:fileId
 * Serve an uploaded lab file by its fileId (UUID without extension).
 */
export async function serveFile(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const fileId = req.params.fileId as string;

    // Also accept token via query param (for window.open from frontend)
    const queryToken = typeof req.query.token === "string" ? req.query.token : null;

    // Try: Bearer token → query token → refresh cookie
    let userId: string | null = null;
    const authHeader = req.headers.authorization;
    if (authHeader?.startsWith("Bearer ")) {
      try {
        const payload = verifyAccessToken(authHeader.slice(7));
        userId = payload.sub;
      } catch {
      }
    }
    if (!userId && queryToken) {
      try {
        const payload = verifyAccessToken(queryToken);
        userId = payload.sub;
      } catch {
        // Token invalid, try cookie next
      }
    }
    if (!userId) {
      const refreshCookie = req.cookies?.refreshToken;
      if (refreshCookie) {
        try {
          const payload = verifyRefreshToken(refreshCookie);
          userId = payload.sub;
        } catch {
          // Cookie token also invalid
        }
      }
    }
    if (!userId) {
      res.status(401).json({ error: { code: "UNAUTHORIZED", message: "Token akses diperlukan" } });
      return;
    }

    // Search for the file in the upload directory by matching UUID prefix
    let foundFile: string | null = null;
    try {
      const files = fs.readdirSync(LAB_UPLOAD_DIR);
      const match = files.find((f) => f.startsWith(fileId));
      if (match) {
        foundFile = path.join(LAB_UPLOAD_DIR, match);
      }
    } catch {
      // Directory read error
    }

    if (!foundFile) {
      res.status(404).json({ code: "FILE_NOT_FOUND", message: "File tidak ditemukan" });
      return;
    }

    // Determine content type from extension
    const ext = path.extname(foundFile).toLowerCase();
    const mimeMap: Record<string, string> = {
      ".pdf": "application/pdf",
      ".jpg": "image/jpeg",
      ".jpeg": "image/jpeg",
      ".png": "image/png",
    };
    const contentType = mimeMap[ext] ?? "application/octet-stream";

    res.setHeader("Content-Type", contentType);
    res.setHeader("Content-Disposition", `inline; filename="lab-${fileId}${ext}"`);
    res.sendFile(foundFile);
  } catch (err) {
    next(err);
  }
}

// ─── Trend (LAB-06) ───────────────────────────────────────────────────────────

/**
 * GET /api/lab/trend?parameter=X&days=30
 * Returns trend data points for a given parameter within the lookback window.
 */
export async function getTrend(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const parameter =
      typeof req.query.parameter === "string" ? req.query.parameter : "";
    const days =
      typeof req.query.days === "string" ? parseInt(req.query.days, 10) || 30 : 30;

    if (!parameter) {
      res.status(400).json({ code: "MISSING_PARAMETER", message: "Parameter namaParameter wajib diisi" });
      return;
    }

    const data = await labResultService.getTrendData(req.user!.id, parameter, days);
    res.json({ parameter, days, data });
  } catch (err) {
    next(err);
  }
}
